### ISSUE TITLE
where is the log?

### ISSUE THREAD

**Issue by jizongFox** [shuaizzZ/Recall-Loss-PyTorch#2]
Hello, 

I checked the code for the recall loss, it seems you directly optimize the recall, instead of using it with the CE loss. 

The paper proposed to use the weighted CE loss non?

Best,

**Comment by shuaizzZ** [comment]
Yes, recall is used as the weight of CE in the paper, but I experimented on my own dataset and found no effect. I will take the time to modify this code.

**Comment by jizongFox** [comment]
@shuaizzZ Your code has no effect since there is no gradient to pass
